### ISSUE TITLE
Requesting access - this is Kevin

### ISSUE THREAD

**Issue by parrotfella** [S-Zell/Recipe-Spot#2]
Do I need to be added as a collaborator to assign labels to issues and such?
This is Kevin by the way :)

**Comment by S-Zell** [comment]
As far as collaboration, either: 
-I can make you a collaborator, and you can make changes anywhere. 
-You can click within your profile to "fork" it, at which point you get a copy. You make changes, and click commit. Then, you make a pull request, and we merge your fork with the main branch. In theory :).

**Comment by S-Zell** [comment]
I'm going to go ahead and do direct collaboration, and we can perhaps test some forking and pull request merging from some "customer" accounts.

**Comment by parrotfella** [comment]
That works for me. I wanted to be a direct collaborator (like you made me) in order to flag things with labels, thank you.

Going to close this issue now that I'm authorized as a collaborator :)

**Comment by parrotfella** [comment]
I added some labels and assigned this to myself to test the feature!
